### ISSUE TITLE
ECH Website meeting Aug 5, 2024

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/ech-website-v3#21]
### Task List
**Supporters**
- [x] Add Octant, Moloch, EthStakers, FEM, OP

**Get involved**
- [x] Remove extra button for "Join Discord"
- [x] Add ECH Onboarding form link to [Join](https://www.ethcatherders.com/join)
- [x] Add sections to get involved with ECH and Ethereum Community
- [x] Remove Discord image

**What is Eth Cat Herders?**
- [x] either `EthCatHerders` or `Ethereum Cat Herders`

**Home page changes**
- [x] Remove Dencun
- [x] Try adding bg "Grey"
- [ ] #27
- [x] #28
- [ ] #29
- [x] Fixing of Copyright 
- [ ] Footer desc. 
- [x] Add Warpcast
   - [ ] Get more information and perhaps create a channel  

**Future**
- [x] Make use of social media to promote the ECH website. 
- [ ] #30
   - [ ] Add as a button or small section on [Pectra](https://www.ethcatherders.com/upgrades/pectra) page

**Comment by poojaranjan** [comment]
## Aug 12, 2024
### Updates
- Minor UI
- Updated Excalidraw for NFT page for EIP authors [for Claim]

### Top tasks for this week 
- [ ] adding the Supporters' tab
  - Octant, Moloch, Update Gitcoin, FEM
- [ ] Redirect the ethereumcatherders.com to ethcatherders.com

**Comment by poojaranjan** [comment]
Created separate Issues for open tasks
